set_property PACKAGE_PIN W5 [get_ports clk]
 set_property IOSTANDARD LVCMOS33 [get_ports clk]
 
set_property PACKAGE_PIN U16 [get_ports {led[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}] 
set_property PACKAGE_PIN E19 [get_ports {led[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}] 
set_property PACKAGE_PIN U19 [get_ports {led[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}] 
set_property PACKAGE_PIN V19 [get_ports {led[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}] 
 
set_property PACKAGE_PIN A14 [get_ports {position[0]}]
  set_property IOSTANDARD LVCMOS33 [get_ports {position[0]}] 
set_property PACKAGE_PIN A16 [get_ports {position[1]}] 
  set_property IOSTANDARD LVCMOS33 [get_ports {position[1]}]
set_property PACKAGE_PIN B15 [get_ports {position[2]}] 
  set_property IOSTANDARD LVCMOS33 [get_ports {position[2]}]
  
set_property PACKAGE_PIN K17 [get_ports {gyroY[0]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gyroY[0]}]
set_property PACKAGE_PIN M18 [get_ports {gyroY[1]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gyroY[1]}]
set_property PACKAGE_PIN N17 [get_ports {gyroY[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gyroY[2]}]
set_property PACKAGE_PIN P18 [get_ports {gyroY[3]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {gyroY[3]}]  

  
set_property PACKAGE_PIN J1 [get_ports servo_l] 
    set_property IOSTANDARD LVCMOS33 [get_ports servo_l]
set_property PACKAGE_PIN L2 [get_ports servo_r] 
    set_property IOSTANDARD LVCMOS33 [get_ports servo_r]
set_property PACKAGE_PIN J2 [get_ports stall_out] 
    set_property IOSTANDARD LVCMOS33 [get_ports stall_out]
    
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}] 
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}] 
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}] 
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]


set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}] 
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]    
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}] 
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]  
    
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}] 
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}] 
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}] 
    set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
    

set_property PACKAGE_PIN P19 [get_ports hSync] 
    set_property IOSTANDARD LVCMOS33 [get_ports hSync] 
set_property PACKAGE_PIN R19 [get_ports vSync] 
    set_property IOSTANDARD LVCMOS33 [get_ports vSync]
